### ISSUE TITLE
icdar2json

### ISSUE THREAD

**Issue by ghost** [kikirizki/pascalvoc2icdar#1]
@kikirizki Can you upload an icdar to json file converter?

**Comment by kikirizki** [comment]
I will upload it soon. Maybe tomorrow or monday

**Comment by ghost** [comment]
Thanks man
pssssst, I am talking about icdar 2019, where that dataset txt groundtruth is like this:
x1,y1,x2,y2,x3,y3,x4,y4

**Comment by ghost** [comment]
:)
https://youtu.be/CdqoNKCCt7A?t=158

**Comment by kikirizki** [comment]
Working on it

**Comment by kikirizki** [comment]
@deepseek Sorry for late reply. Done , I have tested it

**Comment by kikirizki** [comment]
I will upload for older ICDAR too in near future
