### ISSUE TITLE
"imageHeight": 720 & "imageWidth": 1280

### ISSUE THREAD

**Issue by ghost** [kikirizki/pascalvoc2icdar#3]
@kikirizki Thank you for your hard work,

It is noticed that the image height and width are set to a fixed size of 720x1280 for all images.

Can you make each .json have the size of it's image.

**Comment by kikirizki** [comment]
I'm sorry my bad, I forget to refactor the hardcoded stuff

**Comment by kikirizki** [comment]
I'm sorry my bad, I forget to refactor the hardcoded stuff

**Comment by kikirizki** [comment]
fixed
